services:
  mysql:
    image: mysql:8.0
    container_name: PLOCO_database
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: react_ploclo
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: